# Generated by Django 3.1.4 on 2021-03-07 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='static/img/school_placeholder.jpg', upload_to='schoolLogo')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'Schools_tb',
            },
        ),
        migrations.CreateModel(
            name='Genie_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileimg', models.ImageField(default='static/img/profile_placeholder.jpg', upload_to='profilepics')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=30)),
                ('cutoff', models.CharField(max_length=20)),
                ('jamb_score', models.CharField(max_length=20)),
                ('asp_score', models.CharField(max_length=20)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.schools')),
                ('subject1', models.ManyToManyField(to='practise.Subjects')),
            ],
        ),
    ]
