# Generated by Django 3.1.4 on 2021-03-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genie_users',
            options={'verbose_name': 'Genie User', 'verbose_name_plural': 'Genie Users'},
        ),
        migrations.AlterModelTable(
            name='genie_users',
            table='Users_tb',
        ),
    ]
