# Generated by Django 3.1.4 on 2021-03-07 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210307_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genie_users',
            old_name='subject1',
            new_name='subjects',
        ),
    ]
