# Generated by Django 3.1.4 on 2021-03-07 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genie_users',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.courses'),
        ),
    ]
