# Generated by Django 3.1.7 on 2021-03-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210307_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='genie_users',
            name='genieID',
            field=models.CharField(default=2110, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genie_users',
            name='profileimg',
            field=models.ImageField(default='/static/img/profile_placeholder.jpg', upload_to='profilepics'),
        ),
    ]
