# Generated by Django 3.1.4 on 2021-03-09 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0002_auto_20210307_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score_gotten', models.CharField(blank=True, max_length=10, null=True)),
                ('total_max_score', models.CharField(blank=True, max_length=10, null=True)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Test Log',
                'verbose_name_plural': 'Test Logs',
                'db_table': 'testLog_tb',
            },
        ),
        migrations.CreateModel(
            name='TestScripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('score', models.CharField(max_length=50)),
                ('max_score', models.CharField(max_length=50)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practise.testlogs')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practise.subjects')),
            ],
            options={
                'verbose_name': 'Test Script',
                'verbose_name_plural': 'Test Scripts',
                'db_table': 'testScripts_tb',
            },
        ),
    ]
