# Generated by Django 3.1.7 on 2021-03-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0003_testlogs_testscripts'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlogs',
            name='Uid',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
