# Generated by Django 3.2.6 on 2022-05-14 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('cbt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_gotten', models.CharField(blank=True, max_length=10, null=True)),
                ('max_score', models.CharField(blank=True, max_length=10, null=True)),
                ('data', models.TextField()),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'verbose_name': 'Test Log',
                'verbose_name_plural': 'Test Logs',
                'db_table': 'testlogs',
            },
        ),
    ]
