# Generated by Django 3.2.6 on 2022-05-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0002_testlogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testlogs',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='testlogs',
            name='score_gotten',
        ),
        migrations.AddField(
            model_name='testlogs',
            name='max_obtainable',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testlogs',
            name='obtained',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
